openapi: 3.0.3
info:
  title: monsterLab-api
  description: monsterLab-api
  version: 1.0.0
servers:
  - url: 'https://localhost:8080/api/v1'
paths:
  /favorites:
    get:
      tags:
        - favorites
      summary: return that the user has previously favoritted.

